Vidly/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Genre
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }
    }
}

Vidly/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;

namespace Vidly.Controllers
{
    [Authorize]
    public class GenresController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Genres
        [AllowAnonymous]
        public ActionResult Index()
        {
            var genres = _context.Genres.ToList();
            return View(genres);
        }

        // New Genre
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Genre genre)
        {
            if(!ModelState.IsValid)
                return View("New", genre);

            _context.Genres.Add(genre);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Vidly/Views/Genres/Index.cshtml
@model IEnumerable<Vidly.Models.Genre>
@{
    ViewBag.Title = "Index";
}

<h2>Genres</h2>
<div class="notAuth">
    @Html.ActionLink("New Genre", "New")
</div>

<ul>
    @foreach (var genre in Model)
    {
        <li>@genre.Id --- @genre.Name</li>
    }
</ul>

Vidly/Views/Genres/New.cshtml
@model Vidly.Models.Genre
@{
    ViewBag.Title = "New Genre";
}

<h2>New</h2>

@using(Html.BeginForm("Save", "Genres"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>
    <div class="form-group">
        @Html.AntiForgeryToken()
        <input type="submit" value="Save" />
    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}